/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GistPublishPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/gist-api.ts
var import_obsidian = require("obsidian");
var GistApiError = class extends Error {
  constructor(message, status) {
    super(message);
    this.status = status;
    Object.setPrototypeOf(this, GistApiError.prototype);
  }
};
var GistApiClient = class {
  constructor() {
    this.apiVersion = "2026-03-10";
    this.baseUrl = "https://api.github.com/gists";
  }
  /**
   * リクエストヘッダーからトークン情報をサニタイズ（マスク）して返すよ！
   */
  sanitizeHeaders(headers) {
    const sanitized = { ...headers };
    if (sanitized["Authorization"]) {
      const auth = sanitized["Authorization"];
      if (auth.startsWith("Bearer ") && auth.length > 11) {
        sanitized["Authorization"] = `Bearer ${auth.substring(7, 11)}...[MASKED]...`;
      } else {
        sanitized["Authorization"] = "Bearer ...[MASKED]...";
      }
    }
    return sanitized;
  }
  /**
   * トークンのサニタイズ処理を文字列全体に対しても行えるようにする（エラーメッセージ用）
   */
  sanitizeString(str) {
    return str.replace(/(ghp_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9_]{82})/g, "ghp_****[MASKED]****");
  }
  getHeaders(token) {
    return {
      "Accept": "application/vnd.github+json",
      "Authorization": `Bearer ${token}`,
      "X-GitHub-Api-Version": this.apiVersion,
      "User-Agent": "Obsidian-Gist-Publish-Plugin"
    };
  }
  /**
   * トークンの有効性と疎通を確認するよ！ (F1-1, F3-1)
   */
  async testAuthentication(token) {
    const options = {
      url: this.baseUrl,
      method: "GET",
      headers: this.getHeaders(token),
      throw: false
      // エラー時に例外をスローせずステータスコードを返させる
    };
    try {
      const res = await (0, import_obsidian.requestUrl)(options);
      return res.status === 200;
    } catch (e) {
      console.error("Authentication test request failed:", this.sanitizeString(String(e)));
      return false;
    }
  }
  /**
   * 新しいGistを作成するよ！ (F2-2)
   */
  async createGist(token, filename, content, description, isPublic) {
    const payload = {
      description,
      public: isPublic,
      files: {
        [filename]: {
          content
        }
      }
    };
    const options = {
      url: this.baseUrl,
      method: "POST",
      headers: this.getHeaders(token),
      contentType: "application/json",
      body: JSON.stringify(payload)
    };
    try {
      const res = await (0, import_obsidian.requestUrl)(options);
      if (res.status === 201) {
        const data = res.json;
        return data;
      } else {
        throw new GistApiError(`Failed to create Gist. Status: ${res.status}, Body: ${res.text}`, res.status);
      }
    } catch (e) {
      if (e instanceof GistApiError) {
        throw e;
      }
      throw new GistApiError(this.sanitizeString(String(e)));
    }
  }
  /**
   * 既存のGistを更新・リネームするよ！ (F2-3, F2-5)
   */
  async updateGist(token, gistId, filename, content, description, oldFilename) {
    const filesPayload = {};
    if (oldFilename && oldFilename !== filename) {
      filesPayload[oldFilename] = null;
    }
    filesPayload[filename] = {
      content
    };
    const payload = {
      description,
      files: filesPayload
    };
    const options = {
      url: `${this.baseUrl}/${gistId}`,
      method: "PATCH",
      headers: this.getHeaders(token),
      contentType: "application/json",
      body: JSON.stringify(payload)
    };
    try {
      const res = await (0, import_obsidian.requestUrl)(options);
      if (res.status === 200) {
        const data = res.json;
        return data;
      } else {
        throw new GistApiError(`Failed to update Gist. Status: ${res.status}, Body: ${res.text}`, res.status);
      }
    } catch (e) {
      if (e instanceof GistApiError) {
        throw e;
      }
      throw new GistApiError(this.sanitizeString(String(e)));
    }
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  token: "",
  defaultPublic: false
};
var GistPublishSettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Obsidian Publish to Gist Settings" });
    const warningEl = containerEl.createDiv({ cls: "gist-publish-warning" });
    warningEl.style.border = "1px solid var(--background-modifier-border)";
    warningEl.style.padding = "15px";
    warningEl.style.borderRadius = "8px";
    warningEl.style.marginBottom = "20px";
    warningEl.style.backgroundColor = "var(--background-secondary-alt)";
    const warningTitle = warningEl.createEl("strong", { text: "\u{1F512} \u30BB\u30AD\u30E5\u30EA\u30C6\u30A3\u8A2D\u8A08\u306B\u3064\u3044\u3066" });
    warningTitle.style.color = "var(--text-success)";
    warningTitle.style.display = "block";
    warningTitle.style.marginBottom = "8px";
    const warningDesc = warningEl.createEl("p", {
      text: "\u672C\u30D7\u30E9\u30B0\u30A4\u30F3\u306FObsidian\u516C\u5F0F\u306E SecretStorage API \u3092\u5229\u7528\u3057\u3066\u3044\u307E\u3059\u3002\u5B9F\u969B\u306EGitHub\u30C8\u30FC\u30AF\u30F3\u5024\u306F\u30B7\u30B9\u30C6\u30E0\uFF08OS\u306E\u30AD\u30FC\u30C1\u30A7\u30FC\u30F3\u7B49\uFF09\u306B\u5B89\u5168\u306B\u4FDD\u7BA1\u3055\u308C\u3001\u30D7\u30E9\u30B0\u30A4\u30F3\u306E\u8A2D\u5B9A\u30D5\u30A1\u30A4\u30EB\uFF08data.json\uFF09\u306B\u306F\u30C8\u30FC\u30AF\u30F3\u306E\u53C2\u7167\u540D\u306E\u307F\u304C\u4FDD\u5B58\u3055\u308C\u307E\u3059\u3002\u3053\u308C\u306B\u3088\u308A\u3001Vault\u5168\u4F53\u3092\u30EA\u30DD\u30B8\u30C8\u30EA\u7B49\u3067\u516C\u958B\u30FB\u540C\u671F\u3057\u3066\u3044\u3066\u3082\u30C8\u30FC\u30AF\u30F3\u304C\u6F0F\u6D29\u3059\u308B\u30EA\u30B9\u30AF\u306F\u3042\u308A\u307E\u305B\u3093\uFF01\u2728"
    });
    warningDesc.style.fontSize = "0.9em";
    warningDesc.style.margin = "0 0 8px 0";
    const adviceList = warningEl.createEl("ul");
    adviceList.style.fontSize = "0.9em";
    adviceList.style.margin = "0";
    adviceList.style.paddingLeft = "20px";
    const adviceItem1 = adviceList.createEl("li", {
      text: "\u30C8\u30FC\u30AF\u30F3\u3092\u4F5C\u6210\u3059\u308B\u969B\u306F\u3001\u5FC5\u8981\u6700\u5C0F\u9650\u306E\u6A29\u9650\uFF08Classic\u30C8\u30FC\u30AF\u30F3\u306E\u5834\u5408\u306F 'gist' \u30B9\u30B3\u30FC\u30D7\u306E\u307F\u3001Fine-grained\u30C8\u30FC\u30AF\u30F3\u306E\u5834\u5408\u306F Gist \u306E\u66F8\u304D\u8FBC\u307F\u6A29\u9650\u306E\u307F\uFF09\u3092\u4ED8\u4E0E\u3057\u305F\u30C8\u30FC\u30AF\u30F3\u3092\u4F7F\u7528\u3057\u3066\u304F\u3060\u3055\u3044\u3002"
    });
    new import_obsidian2.Setting(containerEl).setName("GitHub Personal Access Token (PAT)").setDesc("SecretStorage\u304B\u3089GitHub\u30A2\u30AF\u30BB\u30B9\u30C8\u30FC\u30AF\u30F3\u3092\u9078\u629E\u307E\u305F\u306F\u4F5C\u6210\u3057\u3066\u304F\u3060\u3055\u3044\u3002").addComponent(
      (el) => new import_obsidian2.SecretComponent(this.app, el).setValue(this.plugin.settings.token).onChange(async (value) => {
        this.plugin.settings.token = value;
        await this.plugin.saveSettings();
      })
    );
    let testStatusEl;
    new import_obsidian2.Setting(containerEl).setName("Test Connection").setDesc("\u8A2D\u5B9A\u3057\u305FGitHub\u30C8\u30FC\u30AF\u30F3\u3067API\u306B\u6B63\u5E38\u306B\u63A5\u7D9A\u3067\u304D\u308B\u304B\u30C6\u30B9\u30C8\u3057\u307E\u3059\u3002").addButton(
      (button) => button.setButtonText("Test").onClick(async () => {
        testStatusEl.setText("\u63A5\u7D9A\u30C6\u30B9\u30C8\u4E2D... \u23F3");
        testStatusEl.style.color = "var(--text-normal)";
        const tokenName = this.plugin.settings.token;
        if (!tokenName) {
          testStatusEl.setText("\u274C \u30C8\u30FC\u30AF\u30F3\u304C\u9078\u629E\u3055\u308C\u3066\u3044\u307E\u305B\u3093\uFF01");
          testStatusEl.style.color = "var(--text-error)";
          return;
        }
        const token = this.app.secretStorage.getSecret(tokenName);
        if (!token) {
          testStatusEl.setText("\u274C \u9078\u629E\u3055\u308C\u305F\u30C8\u30FC\u30AF\u30F3\u306E\u5024\u304C\u7A7A\u3067\u3059\uFF01");
          testStatusEl.style.color = "var(--text-error)";
          return;
        }
        const apiClient = new GistApiClient();
        const success = await apiClient.testAuthentication(token);
        if (success) {
          testStatusEl.setText("\u2705 \u63A5\u7D9A\u6210\u529F\uFF01Gist\u3092\u516C\u958B\u3067\u304D\u307E\u3059\uFF01\u2728");
          testStatusEl.style.color = "var(--text-success)";
        } else {
          testStatusEl.setText("\u274C \u63A5\u7D9A\u5931\u6557\uFF01\u30C8\u30FC\u30AF\u30F3\u3084\u6A29\u9650\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
          testStatusEl.style.color = "var(--text-error)";
        }
      })
    );
    const statusContainer = containerEl.createDiv();
    statusContainer.style.textAlign = "right";
    statusContainer.style.paddingRight = "15px";
    statusContainer.style.marginTop = "-10px";
    testStatusEl = statusContainer.createEl("span", { text: "" });
    testStatusEl.style.fontSize = "0.9em";
    new import_obsidian2.Setting(containerEl).setName("Default Privacy").setDesc("\u65B0\u898FGist\u4F5C\u6210\u6642\u306E\u30C7\u30D5\u30A9\u30EB\u30C8\u306E\u516C\u958B\u72B6\u614B\u3092\u6307\u5B9A\u3057\u307E\u3059\u3002").addDropdown(
      (dropdown) => dropdown.addOption("secret", "Secret (Recommended)").addOption("public", "Public").setValue(this.plugin.settings.defaultPublic ? "public" : "secret").onChange(async (value) => {
        this.plugin.settings.defaultPublic = value === "public";
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/publisher.ts
var import_obsidian4 = require("obsidian");

// src/modal.ts
var import_obsidian3 = require("obsidian");
var GistPublishModal = class extends import_obsidian3.Modal {
  constructor(app, initialTitle, initialIsPublic, onSubmit) {
    super(app);
    this.titleVal = initialTitle;
    this.isPublicVal = initialIsPublic;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Gist \u30D1\u30D6\u30EA\u30C3\u30B7\u30E5\u8A2D\u5B9A\u306E\u78BA\u8A8D" });
    new import_obsidian3.Setting(contentEl).setName("Gist Description").setDesc("Gist\u306E\u8AAC\u660E\u6587\uFF08\u30BF\u30A4\u30C8\u30EB\uFF09\u3092\u8A2D\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002").addText(
      (text) => text.setValue(this.titleVal).onChange((value) => {
        this.titleVal = value;
      })
    );
    new import_obsidian3.Setting(contentEl).setName("\u516C\u958B\u8A2D\u5B9A (Public)").setDesc("\u30AA\u30F3\u306B\u3059\u308B\u3068\u5168\u4F53\u516C\u958B(Public)\u3001\u30AA\u30D5\u306B\u3059\u308B\u3068\u30EA\u30F3\u30AF\u9650\u5B9A\u516C\u958B(Secret)\u306B\u306A\u308A\u307E\u3059\u3002").addToggle(
      (toggle) => toggle.setValue(this.isPublicVal).onChange((value) => {
        this.isPublicVal = value;
      })
    );
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Publish \u{1F680}").setCta().onClick(() => {
        this.onSubmit(this.titleVal, this.isPublicVal);
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/publisher.ts
var GistPublisher = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.apiClient = new GistApiClient();
  }
  /**
   * フロントマターを除去するユーティリティ (F2-4)
   */
  stripFrontmatter(content) {
    const frontmatterRegex = /^---\r?\n[\s\S]*?\r?\n---\r?\n/;
    return content.replace(frontmatterRegex, "");
  }
  /**
   * ノート内の最初のH1タイトルを抽出する (F2-1)
   */
  extractH1Title(content) {
    const strippedContent = this.stripFrontmatter(content);
    const lines = strippedContent.split(/\r?\n/);
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.startsWith("# ")) {
        return trimmed.substring(2).trim();
      }
    }
    return null;
  }
  /**
   * 安全にクリップボードにコピーするフォールバック付きメソッド (F2-1)
   */
  async copyToClipboard(text) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (e) {
      try {
        const textarea = document.createElement("textarea");
        textarea.value = text;
        textarea.style.position = "fixed";
        textarea.style.opacity = "0";
        document.body.appendChild(textarea);
        textarea.focus();
        textarea.select();
        const success = document.execCommand("copy");
        document.body.removeChild(textarea);
        return success;
      } catch (err) {
        console.error("Clipboard copy fallback failed:", err);
        return false;
      }
    }
  }
  /**
   * アクティブノートをパブリッシュするメインロジック (F2-1, F2-2, F2-3, F2-4, F2-5)
   */
  async publishActiveFile() {
    const tokenName = this.plugin.settings.token;
    if (!tokenName) {
      new import_obsidian4.Notice("\u274C GitHub\u30A2\u30AF\u30BB\u30B9\u30C8\u30FC\u30AF\u30F3\u304C\u8A2D\u5B9A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002\u8A2D\u5B9A\u753B\u9762\u3067\u767B\u9332\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
      return;
    }
    const token = this.plugin.app.secretStorage.getSecret(tokenName);
    if (!token) {
      new import_obsidian4.Notice("\u274C \u9078\u629E\u3055\u308C\u305FGitHub\u30A2\u30AF\u30BB\u30B9\u30C8\u30FC\u30AF\u30F3\u306E\u5024\u304C\u7A7A\u304B\u7121\u52B9\u3067\u3059\u3002\u8A2D\u5B9A\u753B\u9762\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
      return;
    }
    const activeFile = this.plugin.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian4.Notice("\u274C \u30A2\u30AF\u30C6\u30A3\u30D6\u306A\u30CE\u30FC\u30C8\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3002");
      return;
    }
    if (activeFile.extension !== "md") {
      new import_obsidian4.Notice("\u274C Markdown\u30D5\u30A1\u30A4\u30EB\u306E\u307F\u30D1\u30D6\u30EA\u30C3\u30B7\u30E5\u53EF\u80FD\u3067\u3059\u3002");
      return;
    }
    const rawContent = await this.plugin.app.vault.read(activeFile);
    const fileCache = this.plugin.app.metadataCache.getFileCache(activeFile);
    const frontmatter = (fileCache == null ? void 0 : fileCache.frontmatter) || {};
    const gistId = frontmatter["gist_id"];
    const gistFilename = frontmatter["gist_filename"];
    const currentFilename = activeFile.name;
    const h1Title = this.extractH1Title(rawContent);
    const description = h1Title || activeFile.basename;
    let isPublic = this.plugin.settings.defaultPublic;
    if (frontmatter["public"] !== void 0) {
      const rawPublic = frontmatter["public"];
      if (typeof rawPublic === "boolean") {
        isPublic = rawPublic;
      } else if (rawPublic === "true") {
        isPublic = true;
      } else if (rawPublic === "false") {
        isPublic = false;
      } else {
        isPublic = false;
      }
    }
    const publishContent = this.stripFrontmatter(rawContent);
    const modal = new GistPublishModal(
      this.plugin.app,
      description,
      isPublic,
      async (finalTitle, finalIsPublic) => {
        new import_obsidian4.Notice("\u{1F4E4} GitHub Gist\u306B\u30A2\u30C3\u30D7\u30ED\u30FC\u30C9\u4E2D... \u23F3");
        try {
          if (!gistId) {
            const res = await this.apiClient.createGist(
              token,
              currentFilename,
              publishContent,
              finalTitle,
              finalIsPublic
            );
            await this.plugin.app.fileManager.processFrontMatter(activeFile, (fm) => {
              fm["gist_id"] = res.id;
              fm["gist_filename"] = currentFilename;
              fm["gist_url"] = res.html_url;
            });
            const copyText = `${finalTitle} ${res.html_url}`;
            const copied = await this.copyToClipboard(copyText);
            new import_obsidian4.Notice(
              `\u{1F389} Gist\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F\uFF01
\u{1F517} \u30AF\u30EA\u30C3\u30D7\u30DC\u30FC\u30C9\u306B\u30B3\u30D4\u30FC\u3057\u307E\u3057\u305F\uFF01
${copied ? "(\u30BF\u30A4\u30C8\u30EB\u3068URL)" : "(\u30B3\u30D4\u30FC\u5931\u6557)"}`
            );
          } else {
            try {
              const res = await this.apiClient.updateGist(
                token,
                gistId,
                currentFilename,
                publishContent,
                finalTitle,
                gistFilename
                // 前回保存されたファイル名 (リネーム検知用)
              );
              await this.plugin.app.fileManager.processFrontMatter(activeFile, (fm) => {
                fm["gist_filename"] = currentFilename;
                fm["gist_url"] = res.html_url;
              });
              const copyText = `${finalTitle} ${res.html_url}`;
              const copied = await this.copyToClipboard(copyText);
              new import_obsidian4.Notice(
                `\u{1F389} Gist\u3092\u66F4\u65B0\u3057\u307E\u3057\u305F\uFF01
\u{1F517} \u30AF\u30EA\u30C3\u30D7\u30DC\u30FC\u30C9\u306B\u30B3\u30D4\u30FC\u3057\u307E\u3057\u305F\uFF01
${copied ? "(\u30BF\u30A4\u30C8\u30EB\u3068URL)" : "(\u30B3\u30D4\u30FC\u5931\u6557)"}`
              );
            } catch (err) {
              if (err instanceof GistApiError && err.status === 404) {
                new import_obsidian4.Notice("\u26A0\uFE0F \u5143\u306EGist\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3002\u524A\u9664\u3055\u308C\u305F\u53EF\u80FD\u6027\u304C\u3042\u308B\u305F\u3081\u3001\u65B0\u898F\u4F5C\u6210\u3057\u307E\u3059... \u23F3");
                const newRes = await this.apiClient.createGist(
                  token,
                  currentFilename,
                  publishContent,
                  finalTitle,
                  finalIsPublic
                );
                await this.plugin.app.fileManager.processFrontMatter(activeFile, (fm) => {
                  fm["gist_id"] = newRes.id;
                  fm["gist_filename"] = currentFilename;
                  fm["gist_url"] = newRes.html_url;
                });
                const copyText = `${finalTitle} ${newRes.html_url}`;
                const copied = await this.copyToClipboard(copyText);
                new import_obsidian4.Notice(
                  `\u{1F389} \u5143\u306EGist\u304C\u898B\u3064\u304B\u3089\u306A\u304B\u3063\u305F\u305F\u3081\u3001\u65B0\u898F\u306BGist\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F\uFF01
\u{1F517} \u30AF\u30EA\u30C3\u30D7\u30DC\u30FC\u30C9\u306B\u30B3\u30D4\u30FC\u3057\u307E\u3057\u305F\uFF01
${copied ? "(\u30BF\u30A4\u30C8\u30EB\u3068URL)" : "(\u30B3\u30D4\u30FC\u5931\u6557)"}`
                );
              } else {
                throw err;
              }
            }
          }
        } catch (e) {
          const errorMsg = String(e);
          console.error("Gist publishing failed:", this.apiClient.sanitizeString(errorMsg));
          new import_obsidian4.Notice(`\u274C \u30D1\u30D6\u30EA\u30C3\u30B7\u30E5\u5931\u6557: ${this.apiClient.sanitizeString(errorMsg)}`);
        }
      }
    );
    modal.open();
  }
};

// src/main.ts
var GistPublishPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    console.log("Loading Gist Publish Plugin...");
    await this.loadSettings();
    this.publisher = new GistPublisher(this);
    this.addSettingTab(new GistPublishSettingsTab(this.app, this));
    this.addRibbonIcon("github", "Publish to Gist", async () => {
      await this.publisher.publishActiveFile();
    });
    this.addCommand({
      id: "publish-active-note-to-gist",
      name: "Publish Active Note to Gist",
      callback: async () => {
        await this.publisher.publishActiveFile();
      }
    });
  }
  async onunload() {
    console.log("Unloading Gist Publish Plugin...");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
